# -*- coding: utf-8 -*-
"""fake job post .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tTOMkeR8ZUGgNN5FQwE9Vz2c-_bBYOjr
"""

!pip install pandas numpy scikit-learn matplotlib seaborn nltk imbalanced-learn xgboost shap

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import re
import nltk
from nltk.corpus import stopwords

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier

from sklearn.metrics import classification_report, roc_auc_score, roc_curve

from imblearn.over_sampling import SMOTE

import pickle
import shap

nltk.download('stopwords')

from google.colab import files
uploaded = files.upload()

import zipfile
import os

# Assuming the zip file contains 'fake_job_postings.csv'
zip_file_name = 'fake_job_postings.csv.zip' # or 'fake_job_postings.csv (1).zip' if that was the name on upload

# Check if the zip file exists, if not, try the other name
if not os.path.exists(zip_file_name):
    zip_file_name = 'fake_job_postings.csv (1).zip'

with zipfile.ZipFile(zip_file_name, 'r') as zip_ref:
    zip_ref.extractall('.')

df = pd.read_csv("fake_job_postings.csv")
df.head()

print(df.info())
print(df['fraudulent'].value_counts())

df.fillna("", inplace=True)

df["text"] = df["title"] + " " + df["description"] + " " + df["requirements"]

stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\W', ' ', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df["clean_text"] = df["text"].apply(clean_text)

tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(df["clean_text"]).toarray()
y = df["fraudulent"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

sm = SMOTE()
X_train, y_train = sm.fit_resample(X_train, y_train)

print("After SMOTE:", np.bincount(y_train))

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train, y_train)

rf = RandomForestClassifier()
rf.fit(X_train, y_train)

mlp = MLPClassifier(max_iter=300)
mlp.fit(X_train, y_train)

xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb.fit(X_train, y_train)

models = [lr, rf, mlp, xgb]

for model in models:
    y_pred = model.predict(X_test)
    print("Model:", model.__class__.__name__)
    print(classification_report(y_test, y_pred))
    print("ROC-AUC:", roc_auc_score(y_test, y_pred))
    print("-"*50)

#all models ROC Curve
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve

models = {
    "Logistic": lr,
    "Random Forest": rf,
    "MLP": mlp,
    "XGBoost": xgb
}

plt.figure()

for name, model in models.items():
    y_prob = model.predict_proba(X_test)[:,1]
    fpr, tpr, _ = roc_curve(y_test, y_prob)
    plt.plot(fpr, tpr, label=name)

plt.plot([0,1], [0,1], 'k--')  # random line
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

#model and TD-IDF vectorizer save
import pickle

pickle.dump(xgb, open("model.pkl", "wb"))
pickle.dump(tfidf, open("vectorizer.pkl", "wb"))

from google.colab import files

files.download("model.pkl")
files.download("vectorizer.pkl")

sample_text = "Urgent hiring work from home no experience high salary"

cleaned = clean_text(sample_text)
vec = tfidf.transform([cleaned]).toarray()

prediction = xgb.predict(vec)

if prediction[0] == 1:
    print("Fraud Job ❌")
else:
    print("Genuine Job ✅")

import shap

explainer = shap.Explainer(xgb)
shap_values = explainer(X_test[:100])

shap.plots.bar(shap_values)

!pip install streamlit

import streamlit as st
import pickle
import re

model = pickle.load(open("model.pkl", "rb"))
vectorizer = pickle.load(open("vectorizer.pkl", "rb"))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'\W', ' ', text)
    return text

st.title("Fraud Job Detection System")

text = st.text_area("Enter Job Description")

if st.button("Predict"):
    cleaned = clean_text(text)
    vec = vectorizer.transform([cleaned]).toarray()
    pred = model.predict(vec)

    if pred[0] == 1:
        st.error("Fraud Job ❌")
    else:
        st.success("Genuine Job ✅")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pickle
# import re
# 
# # Load the model and vectorizer
# model = pickle.load(open("model.pkl", "rb"))
# vectorizer = pickle.load(open("vectorizer.pkl", "rb"))
# 
# def clean_text(text):
#     text = text.lower()
#     text = re.sub(r'\W', ' ', text)
#     return text
# 
# st.title("Fraud Job Detection System")
# 
# text = st.text_area("Enter Job Description")
# 
# if st.button("Predict"):
#     cleaned = clean_text(text)
#     vec = vectorizer.transform([cleaned]).toarray()
#     pred = model.predict(vec)
# 
#     if pred[0] == 1:
#         st.error("Fraud Job ❌")
#     else:
#         st.success("Genuine Job ✅")

!streamlit run app.py

!streamlit run app.py & npx localtunnel --port 8501



!pkill -f streamlit
!streamlit run app.py & npx localtunnel --port 8501

